<?php
//$this->placeholder('meta')->set('');
?>

<style>
<!--
body {
	background-color: #ddd; /* Background color */
	color: #222; /* Foreground color used for text */
	font-family: Helvetica;
	font-size: 14px;
	margin: 0;
	/* Amount of negative space around the outside of the body */
	padding: 0;
	/* Amount of negative space around the inside of the body */
}

#header h1 {
	margin: 0;
	padding: 0;
}

#header h1 a {
	background-color: #ccc;
	border-bottom: 1px solid #666;
	color: #fff;
	display: block;
	font-size: 24px;
	font-weight: bold;
	padding: 10px 0;
	text-align: center;
	text-decoration: none;
	background-image: -webkit-gradient(linear, left top, left bottom, from(#5cf060), to(#28742a));
}

fieldset {
	width: 280px;
	-webkit-border-radius: 10px;
	margin: 20px auto auto;
	padding: 10px;
	color: black;
	background-color: white;
	border: 1px solid silver;
	-webkit-box-shadow: 5px 5px 5px gray;
}

td {
	color: #606060;
	font-weight: bold;
	padding: 5px;
}

input[type="submit"]
{
	color: white;
	background-color: #3a3a3a;
	width: 110px;
	height: 30px;
	margin-top: 20px;
	margin-bottom: 20px;
	border: 2px outset gray;
	-webkit-border-radius: 20px;
}

input[type="text"]
{
	
	width: 130px;
	height: 30px;
	padding: 5px;
	margin-top: 10px;
	border: 1px solid gray;
	-webkit-border-radius: 5px;
}
input[type="password"]
{
	
	width: 130px;
	height: 30px;
	padding: 5px;
	margin-top: 10px;
	border: 1px solid gray;
	-webkit-border-radius: 5px;
}
-->
</style>

<div id="header">
<h1><a>Acesso Restrito</a></h1>
</div>
<fieldset>
<div align="center">

<img src="/images/LOGO-F3-NOVO.png" />
<br />
<?=$this->form;?>

</div>
</fieldset>


