<div align="center" style="padding-top: 20px"><br />

<h4>Obras em Produ&ccedil;&atilde;o</h4>
<table id="the-table-cliche">
	<tr>
		<th>Reg</th>
		<th>Situa&ccedil;&atilde;o</th>
		<th>Descri&ccedil;&atilde;o</th>
		<th>C&oacute;digo</th>
		<th>OC</th>
		<th>Data<br />
		In&iacute;cio</th>
		<th>Data<br />
		Pedida</th>
		<th>Qtd<br />
		Pedida</th>
	</tr>
<?php
$i = 1;
$color = new RPS_Styles_RowColor();
$color->setColors('white', '#eff9fe');
$todayPHP = date('Y-m-d');

foreach ($this->jobProducao as $name) :
    if (date('l') == "Friday") {
        $today = new Zend_Date();
        $dayT = $today->add('3', Zend_Date::DAY);
        $tomorrow = date('Y') . '-' . RPS_Helpers_ChangeMonth::changeMonth($dayT) . '-' . $dayT;
    } else {
        $today = new Zend_Date();
        $dayT = $today->add('1', Zend_Date::DAY);
        $tomorrow = date('Y') . '-' . RPS_Helpers_ChangeMonth::changeMonth($dayT) . '-' . $dayT;
    }
    if ($name['j_deldate'] == $todayPHP) {
        $rowColor = '#fce8ba';
    } else 
        if ($name['j_deldate'] == $tomorrow) {
            $rowColor = '#d4ffd5';
        } else 
            if ($name['j_deldate'] < $todayPHP) {
                $rowColor = '#fdd3c8';
            } else {
                $rowColor = $color->display($i);
            }
    ?>
    
    
<tr bgcolor="<?=$rowColor?>">
		<?php if (count($this->obras->getValues($name['j_number'])) > 0 ) : ?>
		<td><a href="/cockpit/id/<?=$this->id['id'];?>/job/<?=$name['j_number'];?>"><?=$name['j_number'];?></a></td>
        <?php else: ?>
		<td><?=$name['j_number'];?></td>
        <?php endif;?>
		<td><?=RPS_Helpers_MachineToHumanCostCenter::translate(RPS_Helpers_JobState::getState($name['j_number']));?></td>
		<td><?=$name['j_title1'];?></td>
		<td><?=$name['j_title2'];?></td>
		<td><?=$name['j_ordnum'];?></td>
		<td><?=RPS_Helpers_Change::date($name['j_datein']);?></td>
		<td><?=RPS_Helpers_Change::date($name['j_deldate']);?></td>
		<td><?=$name['j_qty_ordered'];?></td>

<?php
    $i ++;
endforeach;
?>
</tr>
</table>
<p>
<?=$this->paginationControl($this->jobProducao, 'Sliding', 'pagination.phtml');?>
</p>
</div>