<div class="pagination" align="center">
   
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
              <a href="<?php echo $this->url(array('page' => $this->first)); ?>">In&iacute;cio</a> 
        <?php else: ?>
                <span class="disabled">In&iacute;cio</span> 
        <?php endif; ?>
    
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
              <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt; Anterior</a> 
        <?php else: ?>
            <span class="disabled">&lt; Anterior</span> 
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
            <?php else: ?>
                <?php echo $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
               <a href="<?php echo $this->url(array('page' => $this->next)); ?>">Pr&oacute;ximo &gt;</a> 
        <?php else: ?>
             <span class="disabled">Pr&oacute;ximo &gt;</span> 
        <?php endif; ?>
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
              <a href="<?php echo $this->url(array('page' => $this->last)); ?>">Fim</a>
        <?php else: ?>
            <span class="disabled">Fim</span>
        <?php endif; ?>
        &nbsp; P&aacute;g. <?php echo $this->current; ?> de <?php echo $this->last; ?>
    
 </div>

