<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt" lang="pt">
<head>
<link href="/touch/css/ext-touch.css" media="screen" rel="stylesheet"
	type="text/css" />
<script type="text/javascript" src="/touch/js/ext-touch-debug.js"></script>
<meta name="viewport" content="user-scalable=no, width=device-width" />
<?=$this->placeholder('meta');?>

</head>

<body>



<div id="content"><?=$this->layout()->content?></div>



</body>

</html>
