<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
<meta http-equiv="X-UA-Compatible" content="chrome=1" />
<title>Fernandes &amp; Terceiro, S.A. :: Embalagem Database</title>
<meta name="Copyright" content="Fernandes & Terceiro, S.A." />
<meta name="Author" content="Ricardo Simão - ricardo.simao@fterceiro.pt" />
<meta name="Zend Studio" content="version 7.1.2" />
<meta name="Zend Framework" content="version 10.1.2" />
<meta name="Build" content="03-10" />
<link rel="icon" href="favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" type="text/css" href="/css/stylescockpit.css" />
<script src="/js/jquery-1.4.2.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.custom.min.js"></script>
<link type="text/css" href="/css/redmond/jquery-ui-1.8.custom.css" rel="stylesheet" />
<script type="text/javascript">
$(function(){$('#tabs').tabs({ fx: { opacity: 'toggle' }});});
</script>
<!--[if lt IE 10]>
<script type="text/javascript" src="/js/corner.js"></script>
<script type="text/javascript">
$('.splash').corner();
</script>
<![endif]-->
</head>
<body>
<div id="doc3" class="yui-t1">
<div id="hd">
<div id="header">
<h1>F3 Embalagem DB Cliente - <?=ucfirst(RPS_Helpers_DefineControllerName::controllerName());?></h1>
<div id="home">
<?=$this->Toolbar();?>
</div>
</div>
</div>
<div id="bd">
<div id="yui-main">
<div class="yui-b">
<div class="content"><?=$this->layout()->content;?></div>

</div>
</div>
<div class="yui-b">
<div id="secondary">

</div>
</div>
</div>
<div id="ft">
<div id="footer">Footer</div>
</div>
</div>
<div id="footer" align="center"><p>&copy<?=date(Zend_Date::YEAR_8601);?> Fernandes &amp; Terceiro, S.A. | Todos os direitos reservados.</p></div>
</body>
</html>





