<?=$this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
<?=$this->headTitle();?>
<?=$this->headMeta();?>
<link rel="stylesheet" type="text/css" href="/css/stylescockpit.css" />
<script src="/js/jquery-1.4.2.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.custom.min.js"></script>
<link type="text/css" href="/css/redmond/jquery-ui-1.8.custom.css" rel="stylesheet" />
<script type="text/javascript">
$(function(){$('#tabs').tabs({ fx: { opacity: 'toggle' }});});
</script>
<!--[if lt IE 10]>
<script type="text/javascript" src="/js/corner.js"></script>
<script type="text/javascript">
$('.splash').corner();
</script>
<![endif]-->
</head>
<body>

  <div id="header">
  <h1>F3 Embalagem DB Cliente - <?=ucfirst(RPS_Helpers_DefineControllerName::controllerName());?></h1>
    <div id="home">
<?=$this->Toolbar();?>
</div>
  </div>
<div id="container">  
  <div id="wrapper">
    <div id="content">
      <?=$this->layout()->content;?>
