<div align="center">
<div id="noauth">
<h2>ERRO - SEM PERMISS&Atilde;O</h2>
<br />
<p>N&atilde;o tem permiss&atilde;o para aceder a este recurso da aplica&ccedil;&atilde;o.
<br />
Se acha que &eacute; um erro, contacte o <a href="http://contactos.fterceiro.pt/contactos/sysadmin">Administrador de Sistemas da F3.</a></p>
<script type="text/javascript">
$(document).ready(function(){
    $('#image-no-content').hide();
    $('#image-no-content').show("bounce", 1000);
});
</script>
<div id="image-no-content">
<img src="/images/2.0/no_auth.png" alt="No content" />
</div>

</div>
</div>